name: PHPunit

on: [push, pull_request]

jobs:
    phpunit:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.4']
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  tools: prestissimo, phive
                  extensions: intl

            - name: Install Composer deps
              run: |
                  composer update --no-interaction --no-suggest

            - name: Run PHPunit
              run: |
                  ./vendor/bin/phpunit --verbose --debug
              env:
                  SYMFONY_DEPRECATIONS_HELPER: weak_vendors

            - name: Change paths in clover.xml
              run: |
                  sed -i 's+/home/runner/work/PHPValueObjects/PHPValueObjects+/github/workspace+g' ./build/logs/clover.xml

            - name: Sonarcloud
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
